stages:
  - performance

gatling_performance_test:
  stage: performance
  image: hseeberger/scala-sbt:graalvm-ce-21.3.0-java17_1.6.2_3.1.1
  script:
    - sbt clean compile
    - sbt "gatling:testOnly simulations.BasicSimulation"
  artifacts:
    when: always
    paths:
      - target/gatling/
    expire_in: 1 week

  cache:
    key: sbt-cache
    paths:
      - ~/.ivy2/cache
      - ~/.sbt
      - ~/.coursier

include:
  - .performance-test-pipeline.yml