image: hseeberger/scala-sbt:${JAVA_VERSION}_${SBT_VERSION}_${SCALA_VERSION}

stages:
  - performance

variables:
  # runner image config
  JAVA_VERSION: "graalvm-ce-21.3.0-java17"
  SBT_VERSION: "1.6.2"
  SCALA_VERSION: "2.13.8"

gatling_test:
  stage: performance
  cache:
    key: sbt-cache
    paths:
      - .ivy2/cache
      - .sbt
      - .coursier
  before_script:
    - export SBT_IVY_HOME=$CI_PROJECT_DIR/.ivy2
    - export COURSIER_CACHE=$CI_PROJECT_DIR/.coursier
    - export SBT_GLOBAL_BASE=$CI_PROJECT_DIR/.sbt
  script:
    - sbt clean compile
    - sbt "Gatling / testOnly perf.load.Debug"
  artifacts:
    when: always
    paths:
      - target/gatling/
    expire_in: 1 week
